// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    TestSingleFileComponent: typeof import('./src/components/TestSingleFileComponent.vue')['default']
    UseConfirmDialog: typeof import('./src/components/vueUse/use-confirm-dialog.vue')['default']
    UseEventBus: typeof import('./src/components/vueUse/use-event-bus.vue')['default']
    VueUse: typeof import('./src/components/vueUse/index.vue')['default']
  }
}

export { }
